<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HDRRPA2" name="Scripts.AadharTestScript" tests="6" failures="1" timestamp="11 Feb 2019 06:36:59 GMT" time="77.560" errors="0">
  <testcase name="Aadhar_Login_BlankUserName_ValidPwd" time="13.291" classname="Scripts.AadharTestScript"/>
  <testcase name="Aadhar_Login_InvalidUserName" time="14.054" classname="Scripts.AadharTestScript"/>
  <testcase name="Aadhar_Login_ValidUserName_InvalidPwd" time="14.460" classname="Scripts.AadharTestScript"/>
  <testcase name="Aadhar_Login_ValidUserName_ValidPwd" time="7.437" classname="Scripts.AadharTestScript">
    <failure type="com.codoid.products.exception.FilloException" message="No records found">
      <![CDATA[com.codoid.products.exception.FilloException: No records found
	at com.codoid.products.fillo.Recordset.<init>(Recordset.java:40)
	at com.codoid.products.fillo.Connection.executeQuery(Connection.java:69)
	at Scripts.AadharTestScript.Aadhar_Login_ValidUserName_ValidPwd(AadharTestScript.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Aadhar_Login_ValidUserName_ValidPwd -->
  <testcase name="Aadhar_Login_BlankUserName_BlankPwd" time="14.278" classname="Scripts.AadharTestScript"/>
  <testcase name="Aadhar_Login_ValidUserName_BlankPwd" time="14.040" classname="Scripts.AadharTestScript"/>
</testsuite> <!-- Scripts.AadharTestScript -->
